package com.example.angelneria_final_project.domain.enums;

public enum ProductStatus {
    DELETED, AVAILABLE, DISCONTINUED, IN_STOCK, SOLD_OUT, OUT_OF_STOCK, LOW_STOCK, LIMITED_STOCK,
    TEMPORARILY_UNAVAILABLE, ON_REQUEST, MADE_TO_ORDER, CHECK_AVAILABILITY, COMING_SOON,
    UPCOMING_LAUNCH, NEW_ARRIVAL, NEW, PRE_ORDER, PRE_SALE, END_OF_SEASON, LAST_UNITS,
    OBSOLETE, ON_SALE, DISCOUNTED, CLEARANCE, ARCHIVED, DRAFT, PENDING_REVIEW, REFURBISHED,
    LIKE_NEW, USED, WITH_DEFECT, BLEMISHED
}
